package auth.base.user.constant;

public interface ErrorCode {
    /**
     * General error code
     */
    String GENERAL_ERROR_REQUIRE_PARAMS = "ERROR-GENERAL-0000";
    String GENERAL_ERROR_STORE_LOCKED = "ERROR-GENERAL-0001";
    String GENERAL_ERROR_ACCOUNT_LOCKED = "ERROR-GENERAL-0002";
    String GENERAL_ERROR_SHOP_LOCKED = "ERROR-GENERAL-0003";
    String GENERAL_ERROR_STORE_NOT_FOUND = "ERROR-GENERAL-0004";
    String GENERAL_ERROR_ACCOUNT_NOT_FOUND = "ERROR-GENERAL-0005";

    /**
     * Starting error code Account
     */
    String ACCOUNT_ERROR_UNKNOWN = "ERROR-ACCOUNT-0000";
    String ACCOUNT_ERROR_USERNAME_EXIST = "ERROR-ACCOUNT-0001";
    String ACCOUNT_ERROR_NOT_FOUND = "ERROR-ACCOUNT-0002";
    String ACCOUNT_ERROR_WRONG_PASSWORD = "ERROR-ACCOUNT-0003";
    String ACCOUNT_ERROR_WRONG_HASH_RESET_PASS = "ERROR-ACCOUNT-0004";
    String ACCOUNT_ERROR_LOCKED = "ERROR-ACCOUNT-0005";
    String ACCOUNT_ERROR_OPT_INVALID = "ERROR-ACCOUNT-0006";
    String ACCOUNT_ERROR_LOGIN = "ERROR-ACCOUNT-0007";
    String ACCOUNT_ERROR_MERCHANT_LOGIN_ERROR_DEVICE = "ERROR-ACCOUNT-0008";
    String ACCOUNT_ERROR_MERCHANT_LOGIN_ERROR_STORE = "ERROR-ACCOUNT-0009";
    String ACCOUNT_ERROR_MERCHANT_LOGIN_WRONG_STORE = "ERROR-ACCOUNT-0010";
    String ACCOUNT_ERROR_MERCHANT_SERVICE_NOT_REGISTER = "ERROR-ACCOUNT-0011";
    String ACCOUNT_ERROR_NOT_ALLOW_DELETE_SUPPER_ADMIN = "ERROR-ACCOUNT-0012";
}
